### PR TITLE
Script for generating SVD and C-headers

### PR DESCRIPTION
**Pull request by Yangff**
Hi, I create a simple script to generate SVD and headers for all peripherals under 0x44XXXXXX based on all currently knowledges.

I havn't try compile it and it may contain errors for both offset, naming and generated code.

SVD can be imported into ghidra to produce a little more readable code, although mask the real address might cause problem. Or maybe used for svd2rust. I only generated `<peripheral>` but you only need to merge it with original bl602 svd. 

But, I cannot guarantte the correctness of these code..

It contains some research notes from [This Documents](https://github.com/pine64/bl602-docs/tree/main/hardware_notes/registers/phy). 

And, mac_pl is from alios, based on my observation, it should be the same including the offset. While mac_core and ipc is from [here](https://github.com/lupyuen/bl_iot_sdk/blob/master/components/bl602/bl602_wifidrv/bl60x_wifi_driver/reg_mac_core.h).
and [here](https://github.com/lupyuen/bl_iot_sdk/blob/master/components/bl602/bl602_wifidrv/bl60x_wifi_driver/reg_ipc_app.h).

Others are mainly my guess. 

Beside that, it should be pretty simple to add more generate for markdown or other uses.

### extarct related functions 

This step allow you to isolate interested function that access certain addresses for you to analyse. 

Place the ghidra decompiled C code into `./blobs/bl602_demo_wifi.ghidra.c`, ensure that NO SVD is imported. 
Make sure you have `ctags` installed.

```
./extract_funcs.sh | ./getfuncs.py [Intreasted Address, e.g. DAT_44c0] > somefile.c
```

And you can now open `somefile.c` to see the result.

### Update it with your research and generate the result

Open `manualext.py`, modify it in a way you prefer and run it. 

It's straightforward. 

* Use `Peripheral(peripheral('name', address, size))` to define a new peripheral.
* Use `Reg(name, address)` to define a reg
* Use `Field(name, mask)` to define a field where the bits of that field is zero in the mask
* Use `FieldBit(name, bit, len=1)` to define a field with `lsb=bit` and `msb = bit+len-1`
* Use `Buf(name, beginaddress, endaddress, nBytes=4)` to define an array at `[beginaddress, endaddress]`, both side included. `nBytes` is the sizeof each item.
* Use `GenSVD()` to generate SVD for current peripheral.
* Use `GenHeader` to generate C header for cuurent peripheral.

### CODE REVIEW

**Comment by gamelaster** [comment]
Hi @Yangff 
Really great job! Is this final commit, or you plan to add more things?

Also, I can give you an access to nutcracker repositories, so you can push things directly.

Thanks,
gamiee

**Comment by Yangff** [comment]
> Hi @Yangff
> Really great job! Is this final commit, or you plan to add more things?
> 
> Also, I can give you an access to nutcracker repositories, so you can push things directly.
> 
> Thanks,
> gamiee

I'm still adding some extra symbols. Will replay when finish

**Comment by Yangff** [comment]
> Hi @Yangff
> Really great job! Is this final commit, or you plan to add more things?
> 
> Also, I can give you an access to nutcracker repositories, so you can push things directly.
> 
> Thanks,
> gamiee

it should contain all possible symbols for now, not sure if it's correct but I think it can merge now.

I will try replacing existed objects to get some lower level rewrite code. But I'm not sure what to do about higher level like 80211 or even IPs..

**Comment by Yangff** [comment]
found some extra header in https://github.com/jixinintelligence/bl602-604/tree/37f2d7b36b4c2ba6f073029d351551c33f9610f3/components/bl602/bl602_wifi/plf/refip/src/driver/phy/bl602_phy_rf/reg and include them..

that should be all sources..

**Comment by gamelaster** [comment]
@Yangff thanks!

**Pull request merged**
