### PR TITLE
Add generated headers from DWARF info

### PR DESCRIPTION
**Pull request by zigazeljko**
This PR adds (pseudo-)headers generated from DWARF info. Declarations are grouped by names of source files (in which they were defined). Comments at the end of line contain source locations (in form `:line:column`).

### CODE REVIEW

**Comment by WildCryptoFox** [comment]
What command(s) did you use to extract these?

**Comment by zigazeljko** [comment]
I used the builtin [`debug/elf`](https://godoc.org/debug/elf) and [`debug/dwarf`](https://godoc.org/debug/dwarf) packages in Go to parse the DWARF info and wrote some code to output that in C-like format and sort based on source locations.

**Comment by WildCryptoFox** [comment]
Nice. I hope you'll publish this tool. ;)

If you publish the tool. Please add reconstruction instructions to the README in the work log.

**Comment by WildCryptoFox** [comment]
If you publish the tool. Please add reconstruction instructions to the README in the work log.

**Comment by gamelaster** [comment]
Thank you very much for your pull request!

For receiving the free PineCone, please sign up at [this link](https://nutcracker.pine64.org/free-evb/).
(If there will be any issues with signing up, please let me know here).

**Comment by zigazeljko** [comment]
@gamelaster I signed up 2 days ago, but I didn't receive any confirmation email. Can you check if you received my submission?

**Comment by gamelaster** [comment]
Hi @zigazeljko , you should received email, and also, when you log in once again to Nutcracker website, it should give you information about your submission.

**Pull request merged**
