### PR TITLE
Init README, add license, extract archives, disassemble objects.

### PR DESCRIPTION
**Pull request by WildCryptoFox**

### CODE REVIEW

**Comment by gamelaster** [comment]
Thank you very much for your pull request!
For receiving the free PineCone, please sign up at [this link](https://nutcracker.pine64.org/free-evb/).
(If there will be any issues with signing up, please let me know here).

**Comment by WildCryptoFox** [comment]
You're welcome. Thanks for the PineCone! (**Edit**: My entry will be delayed.)

**Comment by gamelaster** [comment]
Sure, no problem, take your time :)

**Comment by WildCryptoFox** [comment]
@gamelaster Can you confirm my entry was added? (It was unclear if the form invalidated itself with time. There was no email notification.)

**Comment by gamelaster** [comment]
@WildCryptoFox I checked it and your entry isn't here. Did you filled your email, name, and shipping address?
Thx

**Comment by WildCryptoFox** [comment]
@gamelaster Resubmitted. I did. I loaded the page when you presented the link, logged into GitHub and soon before my last message, I submitted the form. The form did not show any errors, it only returned me to the "login with GitHub" page. This time it appears to have worked.

Thank you. Still no email, though I don't know if I should expect an automated or manual email.

**Pull request merged**
